server:
  port: 9091

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/UserDb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secretKey: ${java12secret}
  issuer: ${java12issuer}

rabbitmq:
  auth-exchange: authExchange
  register-queue: registerQueue
  register-bindingKey: registerBindingKey

  active-status-queue: activeStatusQueue
  active-status-bindingKey: activeStatusBindingKey