server:
  port: 9091

spring:
  cache:
    type: redis
  data:
    mongodb:
      host: localhost
      port: 27020
      username: java12user
      password: root
      database: userDb

    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service


jwt:
  secretKey: ${java12secret}
  issuer: ${java12issuer}

rabbitmq:
  register-queue: registerQueue
  register-bindingKey: registerBindingKey

  active-status-queue: activeStatusQueue
  active-status-bindingKey: activeStatusBindingKey

  register-elastic-queue: registerElasticQueue
  register-elastic-bindingKey: registerElasticBindingKey
  user-exchange: exchangeUser
